import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import '../public/boxicons/fonts/basic/boxicons.min.css';
import '../public/boxicons/fonts/brands/boxicons-brands.min.css';

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins"
});

export const metadata: Metadata = {
  title: "Bhisma Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${poppins.variable} antialiased`}>{children}</body>
    </html>
  );
}
